"""change time types

Revision ID: 1cbfbfbfcf55
Revises: dcae0d968a39
Create Date: 2024-01-16 20:58:21.417947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbfbfbfcf55'
down_revision = 'dcae0d968a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('time_start',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('time_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('time_end',
               existing_type=sa.String(length=64),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('time_start',
               existing_type=sa.String(length=64),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
